<ul class='nav'>
    <?php

    use Zend\Debug\Debug;
use Zend\Authentication\AuthenticationService;

$auth = new AuthenticationService;
    $user = $auth->getStorage()->read();
    $liClass = '';
    $aAttribs = '';
    $liClasses = array();
    echo '<li' . $liClass . '><a href="' . $this->url('home') . '"' . $aAttribs . '>Página principal</a>';
    echo '<li' . $liClass . '><a href="' . $this->url('logout') . '"' . $aAttribs . '>Sair</a>';
    echo '<li' . $liClass . '><a href="' . $this->url(\str_replace(' ','-',strtolower($user['departamento']))) . '"' . $aAttribs . '>Painel</a>';
//    echo '<li class="divider-vertical"></li>';
//    foreach ($this->container as $page):
//        $liClass = '';
//        $aAttribs = '';
//        $liClasses = array();
//
//        
//
//            $sub = $page->getPages();
//          
//
//            if ($page->isActive())
//                $liClasses[] = 'active';
//            if (count($sub) > 0):
//                $liClasses[] = 'dropdown';
//                $aAttribs = ' class="dropdown-toggle" data-toggle="dropdown"';
//            endif;
//            if (count($liClasses) > 0)
//                $liClass = ' class="' . implode(' ', $liClasses) . '"';
//            echo '<li' . $liClass . '><a href="' . $this->url($page->getRoute()) . '"' . $aAttribs . '>' . $page->getlabel() . '</a>';
//            if (count($sub) > 0):
//                echo '<ul class="dropdown-menu">';
//                foreach ($sub as $pages):
//                    $param = $pages->getParams();
//                    $active = $pages->isActive() ? ' class="active"' : '';
//                    echo '<li' . $active . '><a href="' . $this->url($pages->getRoute(), array('action' => $pages->getAction(), 'setor' => $param['setor'])) . '">' . $pages->getlabel() . '</a></li>';
//                endforeach;
//                echo '</ul></li>';
//            else:
//                echo '</li>';
//           
//            unset($aAttribs, $liClass, $liClasses);
//        endif;
//    endforeach;
    ?>
</ul>