<div class="hero-unit">
    <div class="buttongrande"><a href="<?php echo $this->url('helpdesk',array('setor'=>1))?>"><img src="/images/solicitacaoti.fw.png"/><br/><small>Solicitação de T.I.</small></a></div>
    <div class="buttongrande"><a href="<?php echo $this->url('helpdesk',array('setor'=>2))?>"><img src="/images/solicitacaope.fw.png"/><br/><small>Solicitação de Projetos Especiais</small></a></div>
</div>
