<?php
use Zend\Authentication\AuthenticationService;
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('IRM Net - Intranet')->setSeparator(' : ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        $this->HeadLink()
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        echo $this->HeadLink()
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile($this->basePath() . '/js/jquery.editinplace.js')
        ?>


    </head>
    <body>
        <?php $this->placeholder('barrasup')->captureStart(); ?>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">                     
                    <div class="nav-collapse collapse">
                        <?php echo $this->navigation('Navigation')->menu()->setPartial(array('partials/navigation.phtml', 'default'))->render(); ?>                       
                    </div>
                </div>
            </div>
        </div>
        <?php $this->placeholder('barrasup')->captureEnd(); ?>
        <?php
        $auth = new AuthenticationService;
        echo $auth->hasIdentity() ? $this->placeholder('barrasup') : '';
        ?>
        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y'); ?> IRM Services <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
