<?php
use Zend\Authentication\AuthenticationService;
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('IRM Net - Intranet')->setSeparator(' : ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        $this->HeadLink()
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
             
                ->appendStylesheet('http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css')
   
                
                ->appendStylesheet($this->basePath() . '/js/pe.kenburns/themes/neutral/skin.min.css') 
                ->appendStylesheet($this->basePath() . '/css/multi-select.css') 
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/css/barra-base.css');
                
                ;
        echo $this->HeadLink()
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile($this->basePath() . '/js/jquery.editinplace.js')
              
                ->appendFile($this->basePath() . '/js/pe.kenburns/jquery.pixelentity.kenburnsSlider.min.js')
                ->appendFile($this->basePath() . '/js/jquery.multi-select.js')
        ?> 


    </head>
    <body>
        <?php
        $auth = new AuthenticationService;
        $user = $auth->getStorage()->read();
        
        if(!empty($user)):?>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">                     
                    <div class="nav-collapse collapse">
                        <?php 
                          $liClass = '';
    $aAttribs = '';
    $liClasses = array();
     $liClass = ' class="' . implode(' ', $liClasses) . '"';
//                            echo '<li' . $liClass . '><a href="' . $this->url('home') . '"' . $aAttribs . '>Página principal</a>';
//    echo '<li' . $liClass . '><a href="' . $this->url('logout') . '"' . $aAttribs . '>Sair</a>';
//    echo '<li' . $liClass . '><a href="' . $this->url(\str_replace(' ','-',strtolower($user['departamento']))) . '"' . $aAttribs . '>Painel</a>';
                         echo $this->navigation('Navigation')->menu()->setPartial(array('partials/navigation.phtml', 'default'))->render();
//                        switch(strtolower($user['departamento']))
//                        {
//                            case 'ti':
//                                echo $this->navigation('Navigation')->menu()->setPartial(array('partials/navigation.phtml', 'ti-navigation'))->render();
//                                break;
//                            case 'projetos especiais':
//                                echo $this->navigation('Navigation')->menu()->setPartial(array('partials/navigation.phtml', 'pe-navigation'))->render();
//                                break;
//                            default:
//                                echo $this->navigation('Navigation')->menu()->setPartial(array('partials/navigation.phtml', 'navigation'))->render();
//                                break;
//                        }
                         ?>                       
                    </div>
                </div>
            </div>
        </div>
        <?php endif;?>
      
        <div class="container">
            <?php echo $this->content; ?>
         <?php if(!empty($user)):?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y'); ?> IRM Services <?php echo $this->translate('All rights reserved.') ?><span class="pull-right">Logado como: <?php echo $user['displayname']?></p>
            </footer>
            <?php endif;?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
